package br.rainformatica.pontoweb.entity;

// Generated 23/01/2014 17:41:24 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
  
/**
 * TbClientes generated by hbm2java
 */
@Entity
@Table(name = "tb_clientes", catalog = "db_ponto")
public class TbClientes implements java.io.Serializable {

	private Integer idTbClientes;
	private String nome;
	private Set<TbProjeto> tbProjetos = new HashSet<TbProjeto>(0);
	private Set<TbHorasColab> tbHorasColabs = new HashSet<TbHorasColab>(0);
	private Set<TbHorasProjetos> tbHorasProjetos = new HashSet<TbHorasProjetos>(0);

	public TbClientes() {
	}

	public TbClientes(String nome, Set<TbProjeto> tbProjetos,
			Set<TbHorasColab> tbHorasColabs, Set<TbHorasProjetos> tbHorasProjetos) {
		this.nome = nome;
		this.tbProjetos = tbProjetos;
		this.tbHorasColabs = tbHorasColabs;
		this.tbHorasProjetos = tbHorasProjetos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_Tb_Clientes", unique = true, nullable = false)
	public Integer getIdTbClientes() {
		return this.idTbClientes;
	}

	public void setIdTbClientes(Integer idTbClientes) {
		this.idTbClientes = idTbClientes;
	}

	@Column(name = "nome")
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbClientes")
	public Set<TbProjeto> getTbProjetos() {
		return this.tbProjetos;
	}

	public void setTbProjetos(Set<TbProjeto> tbProjetos) {
		this.tbProjetos = tbProjetos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbClientes")
	public Set<TbHorasColab> getTbHorasColabs() {
		return this.tbHorasColabs;
	}

	public void setTbHorasColabs(Set<TbHorasColab> tbHorasColabs) {
		this.tbHorasColabs = tbHorasColabs;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbClientes")
	public Set<TbHorasProjetos> getTbHorasProjetos() {
		return this.tbHorasProjetos;
	}

	public void setTbHorasProjetos(Set<TbHorasProjetos> tbHorasProjetos) {
		this.tbHorasProjetos = tbHorasProjetos;
	}

}
