package br.rainformatica.pontoweb.entity;

// Generated 27/01/2014 10:16:12 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.OneToMany;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbHorasAdicionais generated by hbm2java
 */
@Entity
@Table(name = "tb_horas_adicionais", catalog = "db_ponto")
public class TbHorasAdicionais implements java.io.Serializable {

	private Integer idTbHorasAdicionais;
	private TbProjeto idTbProjeto;
	private TbAnalista idTbAnalista;
	private Integer totalHoras;
	private Set<TbHorasColab> tbHorasColab = new HashSet<TbHorasColab>(0);

	public TbHorasAdicionais() {
	}

	public TbHorasAdicionais(TbProjeto idTbProjeto, TbAnalista idTbAnalista,
			Integer totalHoras, Set<TbHorasColab> tbHorasColab) {
		this.idTbProjeto = idTbProjeto;
		this.idTbAnalista = idTbAnalista;
		this.totalHoras = totalHoras;
		this.tbHorasColab = tbHorasColab;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_tb_horas_adicionais", unique = true, nullable = false)
	public Integer getIdTbHorasAdicionais() {
		return this.idTbHorasAdicionais;
	}

	public void setIdTbHorasAdicionais(Integer idTbHorasAdicionais) {
		this.idTbHorasAdicionais = idTbHorasAdicionais;
	}

	@Column(name = "id_tb_projeto")
	public TbProjeto getIdTbProjeto() {
		return this.idTbProjeto;
	}

	public void setIdTbProjeto(TbProjeto idTbProjeto) {
		this.idTbProjeto = idTbProjeto;
	}

	@Column(name = "id_tb_analista")
	public TbAnalista getIdTbAnalista() {
		return this.idTbAnalista;
	}

	public void setIdTbAnalista(TbAnalista idTbAnalista) {
		this.idTbAnalista = idTbAnalista;
	}

	@Column(name = "total_horas")
	public Integer getTotalHoras() {
		return this.totalHoras;
	}

	public void setTotalHoras(Integer totalHoras) {
		this.totalHoras = totalHoras;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbHorasAdicionais")
	public Set<TbHorasColab> getTbHorasColab() {
		return tbHorasColab;
	}

	public void setTbHorasColab(Set<TbHorasColab> tbHorasColab) {
		this.tbHorasColab = tbHorasColab;
	}

}
