package br.rainformatica.pontoweb.entity;

// Generated 23/01/2014 17:41:24 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cascade;
import org.hibernate.validator.NotNull;

/**
 * TbHorasColab generated by hbm2java
 */
@Entity
@Table(name = "tb_horas_colab", catalog = "db_ponto")
public class TbHorasColab implements java.io.Serializable {

	private Integer idTbHorasColab;
	private TbAnalista tbAnalista;
	private TbClientes tbClientes;
	private TbProjeto tbProjeto;
	private Date data;
	private String descAtividade;
	private String diaSemana;
	private Date entrada;
	private Integer horasAdicionais;
	private Date retornoAlmoco;
	private Date saida;
	private Date saidaAlmoco;
	private Date totalHoras;
	private TbHorasAdicionais tbHorasAdicionais;
	private TbHorasProjetos tbHorasProjetos;

	public TbHorasColab() {
	}

	public TbHorasColab(TbAnalista tbAnalista, TbClientes tbClientes,
			TbProjeto tbProjeto, TbHorasAdicionais tbHorasAdicionais, TbHorasProjetos tbHorasProjetos) {
		this.tbAnalista = tbAnalista;
		this.tbClientes = tbClientes;
		this.tbProjeto = tbProjeto;
		this.tbHorasAdicionais = tbHorasAdicionais;
		this.tbHorasProjetos = tbHorasProjetos;
		
	}

	public TbHorasColab(TbAnalista tbAnalista, TbClientes tbClientes,
			TbProjeto tbProjeto, TbHorasAdicionais tbHorasAdicionais, TbHorasProjetos tbHorasProjetos, Date data, String descAtividade,
			String diaSemana, Date entrada, Integer horasAdicionais,
			Date retornoAlmoco, Date saida, Date saidaAlmoco, Date totalHoras) {
		this.tbAnalista = tbAnalista;
		this.tbClientes = tbClientes;
		this.tbProjeto = tbProjeto;
		this.tbHorasAdicionais = tbHorasAdicionais;
		this.tbHorasProjetos = tbHorasProjetos;
		this.data = data;
		this.descAtividade = descAtividade;
		this.diaSemana = diaSemana;
		this.entrada = entrada;
		this.horasAdicionais = horasAdicionais;
		this.retornoAlmoco = retornoAlmoco;
		this.saida = saida;
		this.saidaAlmoco = saidaAlmoco;
		this.totalHoras = totalHoras;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_Tb_HorasColab", unique = true, nullable = false)
	public Integer getIdTbHorasColab() {
		return this.idTbHorasColab;
	}

	public void setIdTbHorasColab(Integer idTbHorasColab) {
		this.idTbHorasColab = idTbHorasColab;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_analista", nullable = false)
	@NotNull
	public TbAnalista getTbAnalista() {
		return this.tbAnalista;
	}

	public void setTbAnalista(TbAnalista tbAnalista) {
		this.tbAnalista = tbAnalista;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cliente", nullable = false)
	@NotNull
	public TbClientes getTbClientes() {
		return this.tbClientes;
	}

	public void setTbClientes(TbClientes tbClientes) {
		this.tbClientes = tbClientes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_projeto", nullable = false)
	@NotNull
	public TbProjeto getTbProjeto() {
		return this.tbProjeto;
	}

	public void setTbProjeto(TbProjeto tbProjeto) {
		this.tbProjeto = tbProjeto;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_horas_adicionais", nullable = true)
	
	public TbHorasAdicionais getTbHorasAdicionais() {
		return this.tbHorasAdicionais;
	}

	public void setTbHorasAdicionais(TbHorasAdicionais tbHorasAdicionais) {
		this.tbHorasAdicionais = tbHorasAdicionais;
	}
	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.PERSIST)
	@JoinColumn(name = "id_horas_projetos", nullable = true)
	
	public TbHorasProjetos getTbHorasProjetos() {
		return this.tbHorasProjetos;
	}

	public void setTbHorasProjetos(TbHorasProjetos tbHorasProjetos) {
		this.tbHorasProjetos = tbHorasProjetos;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data", length = 10)
	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

	@Column(name = "desc_atividade")
	public String getDescAtividade() {
		return this.descAtividade;
	}

	public void setDescAtividade(String descAtividade) {
		this.descAtividade = descAtividade;
	}

	@Column(name = "dia_semana")
	public String getDiaSemana() {
		return this.diaSemana;
	}

	public void setDiaSemana(String diaSemana) {
		this.diaSemana = diaSemana;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "entrada", length = 8)
	public Date getEntrada() {
		return this.entrada;
	}

	public void setEntrada(Date entrada) {
		this.entrada = entrada;
	}
		
	@Column(name = "horas_adicionais")
	public Integer getHorasAdicionais() {
		return this.horasAdicionais;
	}

	public void setHorasAdicionais(Integer horasAdicionais) {
		this.horasAdicionais = horasAdicionais;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "retorno_almoco", length = 8)
	public Date getRetornoAlmoco() {
		return this.retornoAlmoco;
	}

	public void setRetornoAlmoco(Date retornoAlmoco) {
		this.retornoAlmoco = retornoAlmoco;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "saida", length = 8)
	public Date getSaida() {
		return this.saida;
	}

	public void setSaida(Date saida) {
		this.saida = saida;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "saida_almoco", length = 8)
	public Date getSaidaAlmoco() {
		return this.saidaAlmoco;
	}

	public void setSaidaAlmoco(Date saidaAlmoco) {
		this.saidaAlmoco = saidaAlmoco;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "total_horas")
	public Date getTotalHoras() {
		return this.totalHoras;
	}

	public void setTotalHoras(Date totalHoras) {
		this.totalHoras = totalHoras;
	}

}
