package br.rainformatica.pontoweb.entity;

// Generated 24/01/2014 08:50:03 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbPermissao generated by hbm2java
 */
@Entity
@Table(name = "tb_permissao", catalog = "db_ponto")
public class TbPermissao implements java.io.Serializable {

	private Integer id;
	private String descricao;
	private char tipo;

	public TbPermissao() {
	}

	public TbPermissao(char tipo) {
		this.tipo = tipo;
	}

	public TbPermissao(String descricao, char tipo) {
		this.descricao = descricao;
		this.tipo = tipo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "descricao")
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "tipo", nullable = false, length = 1)
	public char getTipo() {
		return this.tipo;
	}

	public void setTipo(char tipo) {
		this.tipo = tipo;
	}

}
