package br.rainformatica.pontoweb.entity;

// Generated 23/01/2014 17:41:24 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.validator.NotNull;

/**
 * TbUsuarios generated by hbm2java
 */
@Entity
@Table(name = "tb_usuarios", catalog = "db_ponto")
public class TbUsuarios implements java.io.Serializable {

	private Integer idTbUsuario;
	private TbAnalista tbAnalista;
	private String login;
	private String nome;
	private String senha;

	public TbUsuarios() {
	}

	public TbUsuarios(TbAnalista tbAnalista) {
		this.tbAnalista = tbAnalista;
	}

	public TbUsuarios(TbAnalista tbAnalista, String login, String nome,
			String senha) {
		this.tbAnalista = tbAnalista;
		this.login = login;
		this.nome = nome;
		this.senha = senha;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_tb_usuario", unique = true, nullable = false)
	public Integer getIdTbUsuario() {
		return this.idTbUsuario;
	}

	public void setIdTbUsuario(Integer idTbUsuario) {
		this.idTbUsuario = idTbUsuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_analista", nullable = false)
	@NotNull
	public TbAnalista getTbAnalista() {
		return this.tbAnalista;
	}

	public void setTbAnalista(TbAnalista tbAnalista) {
		this.tbAnalista = tbAnalista;
	}

	@Column(name = "login")
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "nome")
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "senha")
	public String getSenha() {
		return this.senha;
	}

	public void setSenha(String senha) {
		this.senha = senha;
	}

}
