package br.rainformatica.pontoweb.entity;

// Generated 24/01/2014 17:56:57 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbDiaSemana generated by hbm2java
 */
@Entity
@Table(name = "tb_dia_semana", catalog = "db_ponto")
public class TbDiaSemana implements java.io.Serializable {

	private Integer id;
	private String descricao;

	public TbDiaSemana() {
	}

	public TbDiaSemana(String descricao) {
		this.descricao = descricao;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "descricao")
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

}
