package br.rainformatica.pontoweb.entity;

// Generated 23/01/2014 17:41:24 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbFuncao generated by hbm2java
 */
@Entity
@Table(name = "tb_funcao", catalog = "db_ponto")
public class TbFuncao implements java.io.Serializable {

	private Integer idTbFuncao;
	private String descricao;

	public TbFuncao() {
	}

	public TbFuncao(String descricao) {
		this.descricao = descricao;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_Tb_Funcao", unique = true, nullable = false)
	public Integer getIdTbFuncao() {
		return this.idTbFuncao;
	}

	public void setIdTbFuncao(Integer idTbFuncao) {
		this.idTbFuncao = idTbFuncao;
	}

	@Column(name = "descricao")
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

}
