package br.rainformatica.pontoweb.entity;

// Generated 17/05/2014 22:16:45 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbHorasProjAnalista generated by hbm2java
 */
@Entity
@Table(name = "tb_horas_proj_analista", catalog = "db_ponto")
public class TbHorasProjAnalista implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idHoraProjAnalista;
	private TbAnalista tbAnalista;
	private TbProjeto tbProjeto;
	private Date horas;
	private Date dataLancamento;
	private TbHorasColab tbHorasColab;
	

	public TbHorasProjAnalista() {
	}

	public TbHorasProjAnalista(TbAnalista tbAnalista, TbProjeto tbProjeto) {
		this.tbAnalista = tbAnalista;
		this.tbProjeto = tbProjeto;
	}

	public TbHorasProjAnalista(TbAnalista tbAnalista, TbProjeto tbProjeto, Date horas,
			Date dataLancamento, TbHorasColab tbHorasColab) {
		this.tbAnalista = tbAnalista;
		this.tbProjeto = tbProjeto;
		this.horas = horas;
		this.dataLancamento = dataLancamento;
		this.tbHorasColab = tbHorasColab;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_hora_proj_analista", unique = true, nullable = false)
	public Integer getIdHoraProjAnalista() {
		return this.idHoraProjAnalista;
	}

	public void setIdHoraProjAnalista(Integer idHoraProjAnalista) {
		this.idHoraProjAnalista = idHoraProjAnalista;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.PERSIST)
	@JoinColumn(name = "id_analista", nullable = false)
	public TbAnalista getTbAnalista() {
		return this.tbAnalista;
	}

	public void setTbAnalista(TbAnalista tbAnalista) {
		this.tbAnalista = tbAnalista;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.PERSIST)
	@JoinColumn(name = "id_projeto", nullable = false)
	public TbProjeto getTbProjeto() {
		return this.tbProjeto;
	}

	public void setTbProjeto(TbProjeto idProjeto) {
		this.tbProjeto = idProjeto;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "horas", length = 8)
	public Date getHoras() {
		return this.horas;
	}

	public void setHoras(Date horas) {
		this.horas = horas;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data_lancamento", length = 10)
	public Date getDataLancamento() {
		return this.dataLancamento;
	}

	public void setDataLancamento(Date dataLancamento) {
		this.dataLancamento = dataLancamento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tb_horascolab", nullable = true)	
	public TbHorasColab getTbHorasColab() {
		return tbHorasColab;
	}

	public void setTbHorasColab(TbHorasColab tbHorasColab) {
		this.tbHorasColab = tbHorasColab;
	}
	

}
