package br.rainformatica.pontoweb.entity;

// Generated 09/05/2014 23:01:12 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.NotNull;

/**
 * TbHorasProjetos generated by hbm2java
 */
@Entity
@Table(name = "tb_horas_projetos", catalog = "db_ponto")
public class TbHorasProjetos implements java.io.Serializable {

	private Integer idHorasProjeto;
	private String projeto1;
	private Date horasProjeto1;
	private String projeto2;
	private Date horasProjeto2;
	private String projeto3;
	private Date horasProjeto3;
	private String projeto4;
	private Date horasProjeto4;
	private String projeto5;
	private Date horasProjeto5;
	private String projeto6;
	private Date horasProjeto6;
	private String projeto7;
	private Date horasProjeto7;
	private String projeto8;
	private Date horasProjeto8;
	private String projeto9;
	private Date horasProjeto9;
	private String projeto10;
	private Date horasProjeto10;
	private TbAnalista tbAnalista;
	private TbClientes tbClientes;
	private Set<TbHorasColab> tbHorasColab = new HashSet<TbHorasColab>(0);
	private Date dataLancamento;
	
	

	public TbHorasProjetos() {
	}
	

	public TbHorasProjetos(String projeto1, Date horasProjeto1, TbAnalista tbAnalista,
			TbClientes tbClientes, TbHorasColab tbHorasColab) {
		this.projeto1 = projeto1;
		this.horasProjeto1 = horasProjeto1;
		this.tbAnalista = tbAnalista;
		this.tbClientes = tbClientes;
		this.tbHorasColab = this.tbHorasColab;
	}

	public TbHorasProjetos(String projeto1, Date horasProjeto1,
			String projeto2, Date horasProjeto2, String projeto3,
			Date horasProjeto3, String projeto4, Date horasProjeto4,
			String projeto5, Date horasProjeto5, String projeto6,
			Date horasProjeto6, String projeto7, Date horasProjeto7,
			String projeto8, Date horasProjeto8, String projeto9,
			Date horasProjeto9, String projeto10, Date horasProjeto10,
			TbAnalista tbAnalista, TbClientes tbClientes, TbHorasColab tbHorasColab, Date dataLancamento) {
		this.projeto1 = projeto1;
		this.horasProjeto1 = horasProjeto1;
		this.projeto2 = projeto2;
		this.horasProjeto2 = horasProjeto2;
		this.projeto3 = projeto3;
		this.horasProjeto3 = horasProjeto3;
		this.projeto4 = projeto4;
		this.horasProjeto4 = horasProjeto4;
		this.projeto5 = projeto5;
		this.horasProjeto5 = horasProjeto5;
		this.projeto6 = projeto6;
		this.horasProjeto6 = horasProjeto6;
		this.projeto7 = projeto7;
		this.horasProjeto7 = horasProjeto7;
		this.projeto8 = projeto8;
		this.horasProjeto8 = horasProjeto8;
		this.projeto9 = projeto9;
		this.horasProjeto9 = horasProjeto9;
		this.projeto10 = projeto10;
		this.horasProjeto10 = horasProjeto10;
		this.tbAnalista = tbAnalista;
		this.tbClientes = tbClientes;
		this.tbHorasColab = this.tbHorasColab;
		this.dataLancamento = dataLancamento;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_horas_projeto", unique = true, nullable = false)
	public Integer getIdHorasProjeto() {
		return this.idHorasProjeto;
	}

	public void setIdHorasProjeto(Integer idHorasProjeto) {
		this.idHorasProjeto = idHorasProjeto;
	}

	@Column(name = "projeto1", nullable = false)
	@NotNull
	public String getProjeto1() {
		return this.projeto1;
	}

	public void setProjeto1(String projeto1) {
		this.projeto1 = projeto1;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "horas_projeto1", nullable = false, length = 8)
	@NotNull
	public Date getHorasProjeto1() {
		return this.horasProjeto1;
	}

	public void setHorasProjeto1(Date horasProjeto1) {
		this.horasProjeto1 = horasProjeto1;
	}

	@Column(name = "projeto2")
	public String getProjeto2() {
		return this.projeto2;
	}

	public void setProjeto2(String projeto2) {
		this.projeto2 = projeto2;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "horas_projeto2", length = 8)
	public Date getHorasProjeto2() {
		return this.horasProjeto2;
	}

	public void setHorasProjeto2(Date horasProjeto2) {
		this.horasProjeto2 = horasProjeto2;
	}

	@Column(name = "projeto3")
	public String getProjeto3() {
		return this.projeto3;
	}

	public void setProjeto3(String projeto3) {
		this.projeto3 = projeto3;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "horas_projeto3", length = 8)
	public Date getHorasProjeto3() {
		return this.horasProjeto3;
	}

	public void setHorasProjeto3(Date horasProjeto3) {
		this.horasProjeto3 = horasProjeto3;
	}

	@Column(name = "projeto4")
	public String getProjeto4() {
		return this.projeto4;
	}

	public void setProjeto4(String projeto4) {
		this.projeto4 = projeto4;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "horas_projeto4", length = 8)
	public Date getHorasProjeto4() {
		return this.horasProjeto4;
	}

	public void setHorasProjeto4(Date horasProjeto4) {
		this.horasProjeto4 = horasProjeto4;
	}

	@Column(name = "projeto5")
	public String getProjeto5() {
		return this.projeto5;
	}

	public void setProjeto5(String projeto5) {
		this.projeto5 = projeto5;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "horas_projeto5", length = 8)
	public Date getHorasProjeto5() {
		return this.horasProjeto5;
	}

	public void setHorasProjeto5(Date horasProjeto5) {
		this.horasProjeto5 = horasProjeto5;
	}

	@Column(name = "projeto6")
	public String getProjeto6() {
		return this.projeto6;
	}

	public void setProjeto6(String projeto6) {
		this.projeto6 = projeto6;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "horas_projeto6", length = 8)
	public Date getHorasProjeto6() {
		return this.horasProjeto6;
	}

	public void setHorasProjeto6(Date horasProjeto6) {
		this.horasProjeto6 = horasProjeto6;
	}

	@Column(name = "projeto7")
	public String getProjeto7() {
		return this.projeto7;
	}

	public void setProjeto7(String projeto7) {
		this.projeto7 = projeto7;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "horas_projeto7", length = 8)
	public Date getHorasProjeto7() {
		return this.horasProjeto7;
	}

	public void setHorasProjeto7(Date horasProjeto7) {
		this.horasProjeto7 = horasProjeto7;
	}

	@Column(name = "projeto8")
	public String getProjeto8() {
		return this.projeto8;
	}

	public void setProjeto8(String projeto8) {
		this.projeto8 = projeto8;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "horas_projeto8", length = 8)
	public Date getHorasProjeto8() {
		return this.horasProjeto8;
	}

	public void setHorasProjeto8(Date horasProjeto8) {
		this.horasProjeto8 = horasProjeto8;
	}

	@Column(name = "projeto9")
	public String getProjeto9() {
		return this.projeto9;
	}

	public void setProjeto9(String projeto9) {
		this.projeto9 = projeto9;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "horas_projeto9", length = 8)
	public Date getHorasProjeto9() {
		return this.horasProjeto9;
	}

	public void setHorasProjeto9(Date horasProjeto9) {
		this.horasProjeto9 = horasProjeto9;
	}

	@Column(name = "projeto10")
	public String getProjeto10() {
		return this.projeto10;
	}

	public void setProjeto10(String projeto10) {
		this.projeto10 = projeto10;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "horas_projeto10", length = 8)
	public Date getHorasProjeto10() {
		return this.horasProjeto10;
	}

	public void setHorasProjeto10(Date horasProjeto10) {
		this.horasProjeto10 = horasProjeto10;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_analista", nullable = false)
	@NotNull
	public TbAnalista getTbAnalista() {
		return tbAnalista;
	}


	public void setTbAnalista(TbAnalista tbAnalista) {
		this.tbAnalista = tbAnalista;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cliente", nullable = false)
	@NotNull
	public TbClientes getTbClientes() {
		return tbClientes;
	}


	public void setTbClientes(TbClientes tbClientes) {
		this.tbClientes = tbClientes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbHorasProjetos")
	public Set<TbHorasColab> getTbHorasColab() {
		return tbHorasColab;
	}

	public void setTbHorasColab(Set<TbHorasColab> tbHorasColab) {
		this.tbHorasColab = tbHorasColab;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data_lancamento", length = 10)
	public Date getDataLancamento() {
		return dataLancamento;
	}


	public void setDataLancamento(Date dataLancamento) {
		this.dataLancamento = dataLancamento;
	}
	
	
	

}
